runcharts:
  - title: Evolution parameters 
    rate-ms: 500        # sampling rate, default = 1000
    scale: 2            # number of digits after sample decimal point, default = 1
    legend:
      enabled: true     # enables item labels, default = true
      details: false    # enables item statistics: cur/min/max/dlt values, default = true
    items:
      - label: Mean
        sample: ./readlog MeanFitness
        color: 178      # 8-bit color number, default one is chosen from a pre-defined palette
      - label: StdDev
        sample: ./readlog StdDeviation
        color: 123      # 8-bit color number, default one is chosen from a pre-defined palette
      - label: Highest
        sample: ./readlog HighestFitness
        color: 54      # 8-bit color number, default one is chosen from a pre-defined palette
