runcharts:
  - title: Evolution parameters 
    rate-ms: 1000
    scale: 2
    legend:
      enabled: true
      details: false
    items:
      - label: Mean
        sample: ./readlog MeanFitness
        color: 178
      - label: StdDev
        sample: ./readlog StdDeviation
        color: 123
      - label: Highest
        sample: ./readlog HighestFitness
        color: 54
