runcharts:
  - title: Fitness
    rate-ms: 1000
    scale: 2
    legend:
      enabled: true
      details: false
    items:
      - label: Mean
        sample: ./readlog MeanFitness
        color: 178
      - label: Highest
        sample: ./readlog HighestFitness
        color: 54
sparklines:
  - title: Deviation
    rate-ms: 1000
    scale: 2
    sample: ./readlog StdDeviation
    color: 123
