#!/bin/bash

if [ "a$1" == "aHighestFitness" ]
then
	tail -n 1 gen.log | sed  's/.* HighestFitness: \[\([0-9\.]*\)\].*/\1/' | cut -d" " -f1
	exit
fi

if [ "a$1" == "aMeanFitness" ]
then
	tail -n 1 gen.log | sed  's/.* MeanFitness: \[\([0-9\.]*\)\].*/\1/' | cut -d" " -f1
	exit
fi

if [ "a$1" == "aStdDeviation" ]
then
	tail -n 1 gen.log | sed  's/.* StdDeviation: \[\([0-9\.]*\)\].*/\1/' | cut -d" " -f1
	exit
fi

echo 0.0
